name: Replace rtp with http in m3u

on:
  workflow_dispatch:
  push:
    paths:
      - 'bj-unicom-iptv.m3u'

jobs:
  replace-rtp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create new m3u with replaced rtp
        run: |
          sed 's|^rtp://|http://router.lan.prpr.one:4022/rtp/|g' bj-unicom-iptv.m3u > bj-unicom-iptv-http.m3u

      - name: Show diff
        run: |
          diff bj-unicom-iptv.m3u bj-unicom-iptv-http.m3u || true
